In [2]:
#split
import numpy as np
arr=np.array([1,2,3,4,5,6])
sub_arrays=np.split(arr,3)

for sub_arr in sub_arrays:
    print(sub_arr)

[1 2]
[3 4]
[5 6]


In [6]:
#sort
arr = np.array([3, 1, 2, 4, 5])
# Sort the array in ascending order (creates a new sorted array)
sorted_arr = np.sort(arr)
# Print the sorted array
print("Sorted array (ascending):", sorted_arr)
# Sort the array in descending order
sorted_arr_desc = np.sort(arr)[::-1]
# Print the sorted array in descending order
print("Sorted array (descending):", sorted_arr_desc)

Sorted array (ascending): [1 2 3 4 5]
Sorted array (descending): [5 4 3 2 1]


In [23]:
# sort for multidimensional arrray
matrix = np.array([[3,1,2 ],
[2, 5, 4]])
# Sort along rows (axis=1) in ascending order
sorted_matrix = np.sort(matrix, axis=1)
# Print the sorted matrix
print("Sorted matrix (ascending along rows):")
print(sorted_matrix)


Sorted matrix (ascending along rows):
[[1 2 3]
 [2 4 5]]


In [12]:
#np.concatenate():The np.concatenate() function is used to join arrays along a specified axis.
#It takes a sequence of arrays as input and concatenates them along the specified axis.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
# Concatenate arr1 and arr2 along rows (vertical)
result = np.concatenate((arr1, arr2), axis=0)
# Print the concatenated array
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
#np.vstack(): Stacks arrays vertically (along rows)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Stack arr1 and arr2 vertically
result = np.vstack((arr1, arr2))
# Print the vertically stacked array
print(result)

[[1 2 3]
 [4 5 6]]


In [17]:
#np.hstack(): Stacks arrays horizontally (along columns)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
# Stack arr1 and arr2 horizontally
result = np.hstack((arr1, arr2))
# Print the horizontally stacked array
print(result)


[1 2 3 4]


In [25]:
#Numpy Filter
#In NumPy, you can filter elements in an array based on a specified condition using boolean indexing.
#Boolean indexing allows you to create a mask (a boolean array) that selects elements from the original array that meet the specified condition.
#Here's how to filter elements in a NumPy array:

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])
# Create a boolean mask based on a condition (e.g., values greater than 3)
mask = (arr > 3)
# Use the mask to filter elements in the array
filtered_array = arr[mask]
# Print the filtered array
print("Filtered Array:", filtered_array)

Filtered Array: [4 5 6]


In [26]:
#Real-Life Scenario: Filtering Sensor Data
# Temperature readings (in Celsius)
temperatures = np.array([20.5, 22.0, 19.8, 23.5, 18.0, 24.2, 26.1])
# Filter temperatures within the range of 20°C to 25°C
filtered_temperatures = temperatures[(temperatures >= 20) & (temperatures <= 25)]
print("Filtered Temperatures:")
print(filtered_temperatures)


Filtered Temperatures:
[20.5 22.  23.5 24.2]


In [28]:
#mean #var #std
#mean
classA= np.array([85, 88, 90, 92, 95])
classA_mean=np.mean(classA)
print('Class A Score Average',classA_mean )
classA_std=np.std(classA)
print('Class A Standard Deviation',classA_std )#std
classA_var=np.var(classA)
print('Class A Variance',classA_var)#var


Class A Score Average 90.0
Class A Standard Deviation 3.40587727318528
Class A Variance 11.6


In [31]:
#np.percentile() - Percentiles:
# Test scores of 30 students
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])
median = np.percentile(test_scores, 30)
print("Median (50th Percentile):", median)


Median (50th Percentile): 97.4


In [30]:
#Saving and Loading NumPy Arrays
# Sample student scores
scores = np.array([85, 92, 78, 88, 95, 72, 89])
# Save the scores to a file
np.save('student_scores.npy', scores)
# Load the scores from the file
loaded_scores = np.load('student_scores.npy')
print("Original Scores:", scores)
print("Loaded Scores:", loaded_scores)

Original Scores: [85 92 78 88 95 72 89]
Loaded Scores: [85 92 78 88 95 72 89]
