In [1]:
#LAB 2
# ques1
#suppose u have a data set containing daily temperature reading s for a city and u want to identify the days with extreme temperature conditions . 
#find days where the temperature either exceeds 35degree C  (hot day) or dropped below 5 degree celsius (cold days)
#input :temperature =np.array ([32.5,.34.2,36.8,29.3,31.0,38.7,23.1,18.5,22.8,37.2])#
import numpy as np
temperature = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])
hot_days = temperature > 35
cold_days = temperature < 5

print("Hot days (temperature > 35°C):")
print("days  temperature")
for i, hot in enumerate(hot_days):
    if hot:
        print(f" {i+1}   {temperature[i]}°C")

print("\nCold days (temperature < 5°C):")

for i, cold in enumerate(cold_days):
    if cold:
        print(f" {i+1}   {temperature[i]}°C")
hot_days_indices = np.where(hot_days)[0]
cold_days_indices = np.where(cold_days)[0]

Hot days (temperature > 35°C):
days  temperature
 3   36.8°C
 6   38.7°C
 10   37.2°C

Cold days (temperature < 5°C):


In [2]:
#ques 2 
''' suppose you have a dataset containing monthly sales data for a company and u want to split this data into a quaterly reports for ananlysis and 
reporting purpose 
input :
monthly_sales=np.array([120,135,140,165,180,155,168,190,205,198,210,225])'''
import numpy as np
monthly_sales = np.array([120, 135, 140, 165, 180, 155, 168, 190, 205, 198, 210, 225])
quarterly_sales = monthly_sales.reshape(4, 3)

# Print quarterly sales data and totals

for i, sales in enumerate(quarterly_sales, start=1):
    print("Quarterly" ,i,"Sales (in thousand of dollars )")
    print(f" {sales}")

Quarterly 1 Sales (in thousand of dollars )
 [120 135 140]
Quarterly 2 Sales (in thousand of dollars )
 [165 180 155]
Quarterly 3 Sales (in thousand of dollars )
 [168 190 205]
Quarterly 4 Sales (in thousand of dollars )
 [198 210 225]


In [6]:
#ques3
#Suppose you have a dataset containing customer data, and you want to split this data into two groups:
#one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days.
#Input:
#customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
#last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
import numpy as np

customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
Active_purchase_condition = last_purchase_days_ago <= 30

Active_customers = customer_ids[Active_purchase_condition]
Not_Active_customers = customer_ids[~Active_purchase_condition]

print("Active Customers(Last purchase<=30)", Active_customers)
print("non_Active Customers(Last purchase<=30)", Not_Active_customers)


Active Customers(Last purchase<=30) [101 102 103 104 105]
non_Active Customers(Last purchase<=30) [106 107 108 109 110]


In [7]:
#ques 4 
'''Suppose you have two sets of employee data—one containing information about
full-time employees and another containing information about part-time employees. You
want to combine this data to create a comprehensive employee dataset for HR analysis.
Input:
# Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])
# Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])'''


import numpy as np
full_time_employees = np.array([
    [101, 'John Doe', 'Full-Time', 55000],
    [102, 'Jane Smith', 'Full-Time', 60000],
    [103, 'Mike Johnson', 'Full-Time', 52000]
], dtype=object)

part_time_employees = np.array([
    [201, 'Alice Brown', 'Part-Time', 25000],
    [202, 'Bob Wilson', 'Part-Time', 28000],
    [203, 'Emily Davis', 'Part-Time', 22000]
], dtype=object)

combined_employees = np.vstack((full_time_employees, part_time_employees))

print("Combined Employee Dataset:")
print(combined_employees)

Combined Employee Dataset:
[[101 'John Doe' 'Full-Time' 55000]
 [102 'Jane Smith' 'Full-Time' 60000]
 [103 'Mike Johnson' 'Full-Time' 52000]
 [201 'Alice Brown' 'Part-Time' 25000]
 [202 'Bob Wilson' 'Part-Time' 28000]
 [203 'Emily Davis' 'Part-Time' 22000]]


In [8]:

# ques 5 
'''How to find the mean of every NumPy array in the given list?
Input:
list = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]'''

import numpy as np
arrays_list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

means = [np.mean(arr) for arr in arrays_list]

# Print the results
print("Means of each NumPy array:")
for i, mean in enumerate(means):
    print(mean)

Means of each NumPy array:
5.5
30.6
34.0


In [9]:
#ques 6 
'''Compute the median of the flattened NumPy array
Input: x_odd = np.array([1, 2, 3, 4, 5, 6, 7])'''

import numpy as np

x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

median_value = np.median(x_odd)
print("the original array ")
print(x_odd)
# Print the result
print(f"The median of the array is: {median_value}")

the original array 
[1 2 3 4 5 6 7]
The median of the array is: 4.0
